### PR TITLE
Update paprika recipe to v1.0.0

### PR DESCRIPTION
**Pull request by slochower**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by slochower** [comment]
Hi,
The linux build on Azure failed with a Syntax Error on line 29 on `paprika/analyze.py` (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=89736&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&taskId=c09a5a47-eec3-5700-9284-6f1bd7b23501&lineStart=684&lineEnd=685&colStart=1&colEnd=1). But line 29-31 reads:

```python
        self.directory = Path(directory_path).joinpath(self.host).joinpath(f"{self.guest}-{guest_orientation}" if
                                                                           guest_orientation is not None else
                                                                           f"{self.guest}")
```

This should be valid Python. Is there something I'm misunderstanding?

**Comment by slochower** [comment]
@conda-forge-admin, please rerender

**Comment by slochower** [comment]
Hi @conda-forge/core,

I'm getting Syntax Errors that I don't quite understand, because they are pointing to valid Python 3.7. Do you have any suggestions?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=90087&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&taskId=ec8d466d-e3b4-5115-4f06-222398f91e6c&lineStart=553&lineEnd=554&colStart=1&colEnd=1

**Comment by isuruf** [comment]
Which python version is installed in the conda test environment?

**Comment by slochower** [comment]
It looks like it's installing Python 3.7: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=90087&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&taskId=ec8d466d-e3b4-5115-4f06-222398f91e6c&lineStart=300&lineEnd=301&colStart=1&colEnd=1

But I agree those issues would pop up if it were installing 2.x for some reason.

**Comment by mbargull** [comment]
It used 2.7. I updated it to use at least 3.6.

**Pull request merged**
